# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/FastAI2022p2",
        "doc_host": "https://devforfu.github.io",
        "git_url": "https://github.com/devforfu/FastAI2022p2",
        "lib_path": "FastAI2022p2",
    },
    "syms": {
        "FastAI2022p2.core": {
            "FastAI2022p2.core.foo": ("core.html#foo", "FastAI2022p2/core.py")
        }
    },
}
